# Project Information
site_name: 传媒网安教学 Wiki
site_description: 黄药师的个人教学 Wiki
site_author: 黄药师
site_url: https://c4pr1c3.github.io/cuc-wiki

# Repository
repo_name: 'c4pr1c3/cuc-wiki'
repo_url: 'https://github.com/c4pr1c3/cuc-wiki'
edit_uri: 'blob/master/docs/'

use_directory_urls: false

nav:
 - '首页': 'index.md'
 - '课程列表': 
   - '密码学应用实践': 'ac.md'
   - '信息安全综合实践': 'cp.md'
   - '网络安全': 'ns.md'
   - '移动互联网安全': 'mis.md'
   - 'Linux 系统与网络管理': 'linux.md'
   - '数据结构A': 'ds.md'
 - '密码学应用实践':
   - '2022年': 'ac/2022/index.md'
   - '2021年': 'ac/2021/index.md'
   - '2019年': 'ac/2019/index.md'
 - '信息安全综合实践':
   - '2022年': 'cp/2022/index.md'
   - '2021年': 'cp/2021/index.md'
   - '2019年': 'cp/2019/index.md'
 - '网络安全':
   - '2021年': 'ns/2021/index.md'
   - '2020年': 'ns/2020/index.md'
   - '2019年': 'ns/2019/index.md'
 - '移动互联网安全':
   - '2021年': 'mis/2021/index.md'
   - '2019年': 'mis/2019/index.md'
 - 'Linux 系统与网络管理':
   - '2022年': 'linux/2022/index.md'
   - '2021年': 'linux/2021/index.md'
   - '2020年': 'linux/2020/index.md'
   - '2019年': 'linux/2019/index.md'
 - '数据结构 A':
   - '2017年': 'ds/2017/index.md'

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

plugins:
  - search

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - codehilite
